Ko.translation patch 1
PDFTron/webviewer-ui pull request #939
Opened 2021-11-30 00:18 UTC by JoYongpil

changed translation

2021-11-30 18:59 UTC, tleepdftron commented on i18n/translation-ko.json
>      "rotate3D": "회전",
3D 회전

2021-11-30 19:18 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "viewShortCutKeysFor3D": "단축키 보기",
3D 툴 단축키 보기

2021-11-30 21:05 UTC, tleepdftron commented on i18n/translation-ko.json
>        "includeReplies": "답글 포함"
댓글 포함

2021-12-01 00:30 UTC, JoYongpil commented on i18n/translation-ko.json
>        "includeReplies": "답글 포함"
translated comment as 댓글
if reply is translated as 댓글, it's overlapped

please check line 11, 12

2021-12-01 17:30 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "noSignatureFields": "이 문서에는 서명필드가 없습니다.",
이 문서에는 서명 양식이 없습니다.

2021-12-01 17:33 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "reply": "답글",
댓글

2021-12-01 17:35 UTC, tleepdftron commented on i18n/translation-ko.json
>      "formFieldEdit": "양식 필드 편집",
양식 영역 편집

2021-12-01 17:40 UTC, tleepdftron commented on i18n/translation-ko.json
>      "pageManipulation": "페이지 조작",
페이지 편집

2021-12-01 17:57 UTC, tleepdftron commented on i18n/translation-ko.json
>      "countMeasurement": "카운트 측정",
측정 수

2021-12-01 18:01 UTC, tleepdftron commented on i18n/translation-ko.json
>      "redact": "개정",
민감한 정보 삭제

2021-12-01 18:02 UTC, tleepdftron commented on i18n/translation-ko.json
>      "squiggly": "곡선",
물결선

2021-12-01 18:02 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "stamp": "이미지",
스탬프

2021-12-01 18:08 UTC, tleepdftron commented on i18n/translation-ko.json
>      "textField": "텍스트 필드",
글쓰기 양식

2021-12-01 18:08 UTC, tleepdftron commented on i18n/translation-ko.json
>      "signatureFormField": "서명 필드",
서명 양식

2021-12-01 18:09 UTC, tleepdftron commented on i18n/translation-ko.json
>      "checkBoxFormField": "체크 박스 필드",
체크박스 양식

2021-12-01 18:10 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "radioButtonFormField": "라디오버튼 필드",
라디오버튼 양식

2021-12-01 18:10 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "listBoxFormField": "목록상자 필드",
목록상자 양식

2021-12-01 18:10 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "comboBoxFormField": "콤보박스 필드",
콤보박스 양식

2021-12-01 18:11 UTC, tleepdftron commented on i18n/translation-ko.json
>      "Experimental": "실험적",
실험

2021-12-01 18:14 UTC, tleepdftron commented on i18n/translation-ko.json
>      "redaction": "개정",
민감한정보 삭제

2021-12-01 18:19 UTC, tleepdftron commented on i18n/translation-ko.json
> +    "noAnnotations": "주석을 달려 댓글을 남깁니다.",
주석을 달아 댓글을 남깁니다.

2021-12-01 18:20 UTC, tleepdftron commented on i18n/translation-ko.json
>      "searchCommentsPlaceholder": "의견 검색",
코멘트 검색

2021-12-01 18:22 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "StrokeColor": "테두리 색상",
글꼴 색

2021-12-01 18:22 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "FillColor": "채우기 색상",
테두리 색

2021-12-01 18:22 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "TextColor": "텍스트 색상"
글꼴 색

2021-12-01 18:24 UTC, tleepdftron commented on i18n/translation-ko.json
>        "markForRedaction": "개정 표시"
민감한 정보 표시

2021-12-01 18:25 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "delete": "지우기",
삭제

2021-12-01 18:26 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "secondaryBtn": "페이지 다운로드 및 제거"
페이지 다운로드 및 삭제

2021-12-01 18:27 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "applyMessage": "편집을 위해 선택된 모든 항목을 영구적으로 제거합니다. 취소 할 수 없습니다."
편집을 위해 선택된 모든 항목을 영구적으로 제거합니다. 제거 후 되돌릴 수 없습니다.

2021-12-01 18:28 UTC, tleepdftron commented on i18n/translation-ko.json
>      "Custom": "커스텀"
사용자

2021-12-01 18:29 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "fieldName": "필드이름",
양식이름

2021-12-01 18:30 UTC, tleepdftron commented on i18n/translation-ko.json
>        "flags": "필드 플래그",
양식 옵션

2021-12-01 18:30 UTC, tleepdftron commented on i18n/translation-ko.json
>        "options": "옵션",
양식 목록

2021-12-01 18:30 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "radioGroups": "동일한 필드이름을 가진 라디오버튼은 동일한 그룹에 속합니다.",
동일한 양식이름을 가진 라디오버튼은 동일한 그룹에 속합니다.

2021-12-01 18:31 UTC, tleepdftron commented on i18n/translation-ko.json
> +      "nameRequired": "필드이름이 필요합니다.",
양식이름이 필요합니다.

2021-12-01 18:31 UTC, tleepdftron commented on i18n/translation-ko.json
> +        "duplicate": "필드이름이 이미 있습니다.",
양식이름이 이미 있습니다.

2021-12-01 18:33 UTC, tleepdftron commented on i18n/translation-ko.json
> +        "empty": "필드이름은 비워 둘 수 없습니다."
양식 이름은 비워 둘 수 없습니다.

2021-12-01 18:34 UTC, tleepdftron commented on i18n/translation-ko.json
>      "type": "필드 유형",
양식 유형

2021-12-01 18:36 UTC, tleepdftron commented on i18n/translation-ko.json
>      "callout": "설명선",
콜아웃

2021-12-01 19:06 UTC, bollain requested changes
Hi @JoYongpil,

Thanks for this PR! We have had a member of our team review the translations and they have left some comments. We also have prepared a mapping of the translations that we think should be updated:
https://www.figma.com/file/pdiWCqBILLzwyHitYRTqRB/WV-Korean-Translation?node-id=0%3A1

Once the changes are made, we will approve and merge this PR.

2021-12-02 01:48 UTC, JoYongpil commented on i18n/translation-ko.json
>        "includeReplies": "답글 포함"
댓글포함

2021-12-02 01:48 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "noSignatureFields": "이 문서에는 서명필드가 없습니다.",
문서에 서명양식이 없습니다.

2021-12-02 01:48 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "reply": "답글",
댓글

2021-12-02 01:49 UTC, JoYongpil commented on i18n/translation-ko.json
>      "formFieldEdit": "양식 필드 편집",
양식영역 편집

2021-12-02 01:49 UTC, JoYongpil commented on i18n/translation-ko.json
>      "pageManipulation": "페이지 조작",
페이지 편집

2021-12-02 01:49 UTC, JoYongpil commented on i18n/translation-ko.json
>      "countMeasurement": "카운트 측정",
측정 수

2021-12-02 01:50 UTC, JoYongpil commented on i18n/translation-ko.json
>      "redact": "개정",
민감 정보 삭제

2021-12-02 01:50 UTC, JoYongpil commented on i18n/translation-ko.json
>      "squiggly": "곡선",
물결선

2021-12-02 01:50 UTC, JoYongpil commented on i18n/translation-ko.json
>      "textField": "텍스트 필드",
텍스트 상자

2021-12-02 01:51 UTC, JoYongpil commented on i18n/translation-ko.json
>      "signatureFormField": "서명 필드",
서명

2021-12-02 01:51 UTC, JoYongpil commented on i18n/translation-ko.json
>      "checkBoxFormField": "체크 박스 필드",
체크박스

2021-12-02 01:51 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "listBoxFormField": "목록상자 필드",
목록상자

2021-12-02 01:52 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "comboBoxFormField": "콤보박스 필드",
콤보박스

2021-12-02 01:52 UTC, JoYongpil commented on i18n/translation-ko.json
>      "redaction": "개정",
민감 정보 삭제

2021-12-02 01:52 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "noAnnotations": "주석을 달려 댓글을 남깁니다.",
주석에 대한 댓글입니다.

2021-12-02 01:53 UTC, JoYongpil commented on i18n/translation-ko.json
>      "searchCommentsPlaceholder": "의견 검색",
코멘트 검색

2021-12-02 01:53 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "StrokeColor": "테두리 색상",
테두리 색

2021-12-02 01:53 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "FillColor": "채우기 색상",
채우기 색

2021-12-02 01:53 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "TextColor": "텍스트 색상"
글자 색

2021-12-02 01:53 UTC, JoYongpil commented on i18n/translation-ko.json
>        "markForRedaction": "개정 표시"
민감한 정보 표시

2021-12-02 01:54 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "delete": "지우기",
삭제

2021-12-02 01:54 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "secondaryBtn": "페이지 다운로드 및 제거"
페이지 다운로드 및 삭제

2021-12-02 01:54 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "applyMessage": "편집을 위해 선택된 모든 항목을 영구적으로 제거합니다. 취소 할 수 없습니다."
편집을 위해 선택된 모든 항목을 영구적으로 제거합니다. 제거 후 되돌릴 수 없습니다.

2021-12-02 01:55 UTC, JoYongpil commented on i18n/translation-ko.json
>      "Custom": "커스텀"
사용자 정의

2021-12-02 01:55 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "fieldName": "필드이름",
양식이름

2021-12-02 01:55 UTC, JoYongpil commented on i18n/translation-ko.json
>        "flags": "필드 플래그",
양식옵션

2021-12-02 01:56 UTC, JoYongpil commented on i18n/translation-ko.json
>        "options": "옵션",
양식목록

2021-12-02 01:56 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "radioGroups": "동일한 필드이름을 가진 라디오버튼은 동일한 그룹에 속합니다.",
동일한 양식이름을 가진 라디오버튼을 동일한 그룹에 속합니다.

2021-12-02 01:56 UTC, JoYongpil commented on i18n/translation-ko.json
> +      "nameRequired": "필드이름이 필요합니다.",
양식이름이 필요합니다.

2021-12-02 01:57 UTC, JoYongpil commented on i18n/translation-ko.json
> +        "duplicate": "필드이름이 이미 있습니다.",
이미 존재하는 양식이름 입니다.

2021-12-02 01:57 UTC, JoYongpil commented on i18n/translation-ko.json
> +        "empty": "필드이름은 비워 둘 수 없습니다."
양식이름은 비워 둘 수 없습니다.

2021-12-02 01:57 UTC, JoYongpil commented on i18n/translation-ko.json
>      "type": "필드 유형",
양식유형

2021-12-02 01:57 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "radioButtonFormField": "라디오버튼 필드",
라디오버튼

2021-12-02 01:58 UTC, JoYongpil commented on i18n/translation-ko.json
> +    "stamp": "이미지",
이미지

2021-12-03 17:10 UTC, tleepdftron commented on i18n/translation-ko.json
>      "comment": "댓글",
Should this be '코멘트'? as 'reply' translated '댓글'

2021-12-03 18:51 UTC, bollain requested changes
One change requested for line 11 "Comment".

2021-12-03 18:51 UTC, bollain commented on i18n/translation-ko.json
>      "comment": "댓글",
As per comments, line 11 should be changed to ` '코멘트'`

2021-12-06 21:05 UTC, bollain approved these changes
All changes made as requested. Reviewed internally by PDFTron. Thanks for your contribution @JoYongpil!

2021-12-06 21:07 UTC, merged