fixed PDFTron intialization bug when no full api is used
PDFTron/webviewer-ui pull request #941
Opened 2021-12-02 13:15 UTC by jhruby

We use XOD files only and when we upgraded to 8.2 we have got following error in the consol
![obrazek-20211202-123404](https://user-images.githubusercontent.com/1236966/144429139-4b7cb50a-cf6e-4e68-a1a7-97444c23056a.png)
e.

This code change has fixed the issue.

2021-12-02 19:41 UTC, bollain commented
Hello @jhruby,

Thanks for this PR. I am not able to reproduce this issue using XOD files, which you can test here:
https://www.pdftron.com/samples/web/samples/viewing/viewing-with-custom-server/

This sample is running 8.2 and loads XOD files. 

Can you provide repro steps for this issue? 

If you wish you can submit a ticket to our support system to track this better.
https://www.pdftron.com/form/request/

2021-12-03 16:11 UTC, jhruby commented
// here is shorter version of our initilization

   WebViewer(
               {
                  licenseKey: "ourlicense",
                  path:  "ourpath",
                  disabledElements: [
                     "thumbMultiDelete",
                     "thumbExtract",
                     "thumbDelete",
                     "dropdown-item-toolbarGroup-FillAndSign",
                     "dropdown-item-toolbarGroup-Insert",
                     "dropdown-item-toolbarGroup-Edit",
                     "dropdown-item-toolbarGroup-Forms",
                     "toolbarGroup-FillAndSign",
                     "toolbarGroup-Insert",
                     "toolbarGroup-Edit",
                     "toolbarGroup-Forms",

                  ],
                  isAdminUser: true,
                  annotationUser: "⠀"
               },
               viewer.current,
            ).then((instance) => {
               const {docViewer} = instance;
              const {Feature} = instance.UI;
             
// probably this
             instance.UI.enableFeatures([Feature.Copy]);

       
});

// here is Feature.Copy intialization
![obrazek](https://user-images.githubusercontent.com/1236966/144634561-cfb5ae55-dbbf-4544-be79-8a3a6de52aaf.png)


// here is hotkeysManager.js where this was failing
![obrazek](https://user-images.githubusercontent.com/1236966/144634430-73d48de7-87a4-41f4-a8e7-849d28762fb1.png)

The hotkeysManager has not been initialized at time where we were calling enableFeatures([Feature.Copy]);  I have moved the initialization prior defineWebViewerInstanceUIAPIs. To make sure that enableFeatures call will not fail.

2021-12-06 20:37 UTC, bollain requested changes
Im able to reproduce this issue, and the fix addresses it. I tested the code and followed the logic and I see no other side effects from moving the initialization of the hotkeys manager.  However, there is one question of some code being moved around.

2021-12-06 20:37 UTC, bollain commented on src/index.js
> -
What is the rationale for moving this down?

2021-12-23 00:17 UTC, bollain commented
Hi @jhruby, I am closing this PR as we fixed this issue internally. You can see the fix here:
https://github.com/PDFTron/webviewer-ui/commit/56ec432655cc1c3ef6b0b96fa9d6ae5395823981

Thanks for your PR we were able to identify this issue, we appreciate your assistance in this regard!

2021-12-23 00:17 UTC, closed without merging